### ISSUE TITLE
Issues importing SHP files

### ISSUE THREAD

**Issue by Balsam-mzh** [neslerel/QGISRed#14]
Hello,
My end of study project aims to integrate a geographic information system (QGIS) with urban network simulation software (EPANET) to develop a solution allowing simulations to be performed directly on this GIS software. For this, I work with the QGISRed extension (version 0.9) but I encounter several problems. When I import shp type layers all the attributes are disappeared and an error message is displayed despite the layers are full of attributes if I import it by the command "add layer" in QGIS (version 3.10.2). Thank you for reading and helping me.
 Cordially.

**Comment by neslerel** [comment]
Hi @Balsam-mzh,

First, I split your issue in two issues. This one about importing shps and other one about deleting elements. In this way, for us it is better in order to control the issues that we fix.

Regarding the importation of shps, can you detail the process and include some captures?
For example, in the importation window, in SHP tab, I selected de folder where the SHPs are located and then, I selected for each type of element, the layer. When the layer is selected, for each property appears the list of attribute fields of the original SHP:
![qgis-bin_2020-03-25_17-15-15](https://user-images.githubusercontent.com/14369655/77559980-1ea18e80-6ebd-11ea-9a74-8250cf1d8eba.png)

You can select for each property the correct field of your original SHP? 
Thanks for write the issue and help us to improve the plugin.

**Comment by Balsam-mzh** [comment]
Thank you for your quick response. I follow the same steps that you
mentioned, but I encounter the same problem even in the previous version. I
forgot to mention that I exported the SHP type files from an
oracle database.

There are some captures:
[image: Sans titre0.png]
[image: Sans titre1.png]
[image: Sans titre2.png]
[image: Sans titre3.png]
[image: Sans titre4.png]
[image: Sans titre.png]


Balsem Marzougui
Élève ingénieur en Génie Hydraulique et Environnement
Ecole Nationale d'Ingénieurs de Tunis, ENIT

**Comment by neslerel** [comment]
Sorry, but images are not be loaded...

About SHPs from oracle database... I don't know if the format is the standar shape files of esri. 
You can try to open these shps with QGis and if it works, you can export each layer to ESRI Shapefile format:
![image](https://user-images.githubusercontent.com/14369655/77569317-4f3bf500-6eca-11ea-9743-7139caa654d4.png)

**Comment by Balsam-mzh** [comment]
Sorry about the captures, I send them in a PDF file.
The layers are already exported in ESRI Shapefile format.

Balsem Marzougui
Élève ingénieur en Génie Hydraulique et Environnement
Ecole Nationale d'Ingénieurs de Tunis, ENIT

**Comment by neslerel** [comment]
Hi @Balsam-mzh,

I don't know if you are importing Tanks from a shapefile. If it is the case, please try to import the other layers without importing Tanks.
Some days ago I detected and fixed an error with this type of element.
In the next version it will be corrected.

**Comment by Balsam-mzh** [comment]
Thank you for your answers. I think that the error in the export of the layers in format shp, I try to have layers format shp by another method and it works.

**Comment by neslerel** [comment]
👏👏
Perfect!
