### ISSUE TITLE
AVISOS: Selected point not over any element

### ISSUE THREAD

**Issue by Broadychill** [neslerel/QGISRed#46]
Hi, 

First of all, thanks for the plugins which looks awsome! 

I try to build a model, but each time a try to create a tank or to delete a pipe, a message apparear which say "AVISOS: Selected point not over any element"

Is it a problem of projection? I'm currently working on a swiss SCR. 

Thanks in advance.

**Comment by neslerel** [comment]
Hi @Broadychill,

Thanks for your positive comment!

Regarding about your problem, yes, it is a projection "problem". I noticed that to be work the different features (create elements, delete, etc.) the projection of the networks layers and the CRS of the QGis project should be the same:
QGis CRS project:
![image](https://user-images.githubusercontent.com/14369655/109823531-502be980-7c38-11eb-8bf9-c13cebbbedb1.png)

Network layers projection:
![image](https://user-images.githubusercontent.com/14369655/109823623-65a11380-7c38-11eb-8f8a-67faad05877b.png)

One question: Your operation system (Windows) is in Spanish? If not, instead of "AVISOS" should be appear "WARNINGS" and maybe something is not working properly.

Thanks!

**Comment by Broadychill** [comment]
Hi, 
Thanks for your answer. 
I'm working on a frensh version of QGIS 3.16. I tried to reinstall the plugin but nothing changed. 
 
All my layers and my project are projected with the CRS CH1903+/LV95. 

Should I work with an other projection? Like a general one? Or it's a bug with the version of QGIS?

**Comment by neslerel** [comment]
If you want, you can send me (nestorlerma@waterpi.com) the QGISRed proyect (zipped) and I can try to test if with my QGis it works fine.
