### ISSUE TITLE
Statistics not working?

### ISSUE THREAD

**Issue by mpalter** [neslerel/QGISRed#86]

**Comment by mpalter** [comment]
Upon further reading previous threads, I have found the answer in that statistics are not shown in the results layers. Apologies for the trouble.

**Comment by fmartine** [comment]
Dear ghost,

- The option to show statistics instead of all-time values is in the roadmap of QGISRed, but perhaps will be available for version 0.18.

In the meanwhile you can use the button statistic of QGIS to carry out all types of statistics from the attribute table of the results themes. But to colour the results according to the statistic values you must do some additional work using more tools of QGIS.
Thank your for using QGISRed
